### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by remingtonc** [pingidentity/pingid-python-samples#1]
Currently this is difficult to decipher due to the lack of documentation. Please improve!

**Comment by asafd1** [comment]
Full API documentation can be found here: https://www.pingidentity.com/content/developer/en/api/pingid-api.html

This repo is only aimed to give python developers an easy start when working with PingID API.
If you feel the python code itself is not clear - please let us know what you feel is missing.

**Comment by remingtonc** [comment]
@asafd1 Thanks for the pointer. Unfortunately I believe the Python code itself is not clear. From my perspective, having no experience with anything PingID, I am not sure how these Python scripts work together or create a workflow. e.g. what is the difference between `startAuthentication.py` and `authOnline.py`? It would be immensely helpful to tie these bits of code back to what they are accomplishing.

EDIT: Even just links to pages in this [documentation](https://www.pingidentity.com/content/developer/en/api/pingid-api/authentication-api.html) would be helpful for those starting out. These docs are helping this make more sense. 👍 

EDIT EDIT: Frankly, what I really want to see is the end-to-end authentication flow. Right now I will have to fiddle for a couple hours with the API to figure out how to do it.

**Comment by asafd1** [comment]
You have a flow example in this (java) repo: https://github.com/asafd1/StartAuthenticationSample

**Comment by asafd1** [comment]
BTW, if you feel like adding code with end-to-end authentication flow - submit a PR and I'd love to add it.

**Comment by remingtonc** [comment]
@asafd1 Thank you for the pointers! Will inspect later this week, and put together a nice PR once I get a better handle on the flow (+some time 👍)!
