### ISSUE TITLE
Availability of  REST APIs to Get list of apps in PingOne , Assign user to an app, remove user from app.

### ISSUE THREAD

**Issue by ghost** [pingidentity/pingid-python-samples#2]
We are trying to integrate PingOne API in our python library. After 2 days of research, I couldn't find any REST API documentation for following use cases.

• List all apps 
• Get an App by Name 
• Assigning an App to a user
• Remove an user from an App

If any one have worked on or having good reference knowledge about ping identity rest API please share helpful documentation link.

**Comment by asafd1** [comment]
AFAIK, there are no public REST APIs for admin management in PingOne.

**Comment by ghost** [comment]
Well , I could find and integrate PingOne REST APIs for User and Group management. Can you suggest any workarround for APP management REST APIS?

**Comment by asafd1** [comment]
I don't know. I would suggest opening a ticket with ping support.

**Comment by ghost** [comment]
Well , already created a ticket..but no response..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
