### ISSUE TITLE
DecodeError calling 'rest/4/getorgreport/do' endpoint

### ISSUE THREAD

**Issue by carbone84** [pingidentity/pingid-python-samples#6]
Not sure if this is a bug or not, but I get a the following error when calling the 'rest/4/getorgreport/do' endpoint after creating a job: jwt.exceptions.DecodeError: Invalid header string: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

It seems to be coming from 'extracted_response = jwt.decode(r.content, key, algorithms=['HS256'])' (line 75) in pingid.py. This works fine when calling to create a job ('rest/4/createjob/do') and get job status ('rest/4/getjobstatus/do'), but these two calls return jwts. The call to get the org report ('rest/4/getorgreport/do') is not returning a jwt. 

Currently, I have worked around this error by editing the pingid.py file. I am checking the content-type of the headers and if they are 'application/octet-stream', I am just sending back the text of the response. Otherwise, I am decoding the content and sending back the extracted response.

`if r.headers['content-type'] == 'application/octet-stream':
    return r.text
else:
    extracted_response = jwt.decode(r.content, key, algorithms=['HS256'])

    if self.verbose:
        print('{0}Response{0}\n{1}\n'.format('='*20, json.dumps(extracted_response, indent=2)))

        return extracted_response`

**Comment by asafd1** [comment]
@carbone84 good catch! can you submit a pull request for that fix?

**Comment by carbone84** [comment]
Submitted. I'll also submit a short script I wrote to create a csv from these endpoints as an example if it'll be useful for others.
